# Basic notes:
# A. builds firejail on 5 different systems for 2 package systems:
#  1. Debian-based systems. Use debian:jessie to ensure reasonable backwards
#  compat and ubuntu:latest for new setups
#  2. Redhat-based systems. Use centos:latest for reasonable backwards compat
#  and fedora:latest for new setups
#  3. Alpine for installing directly from source
#
# B. Run code tests on alpine image (travis CI on GitHub is using Ubuntu Trusty)
build_ubuntu_package:
    image: ubuntu:latest
    script:
    - apt-get update -qq
    - apt-get install -y -qq build-essential lintian
    - ./configure --prefix=/usr && make deb && dpkg -i firejail*.deb

build_debian_package:
  image: debian:jessie
  script:
    - apt-get update -qq
    - apt-get install -y -qq build-essential lintian
    - ./configure --prefix=/usr && make deb && dpkg -i firejail*.deb

build_redhat_package:
    image: centos:latest
    script:
        - yum update -y
        - yum install -y rpm-build gcc make
        - ./configure --prefix=/usr && make rpms && yum install -y firejail*.rpm

build_fedora_package:
    image: fedora:latest
    script:
        - dnf update -y
        - dnf install -y rpm-build gcc make
        - ./configure --prefix=/usr && make rpms && rpm -i firejail*.rpm

build_src_package:
    image: alpine:latest
    script:
        - apk update
        - apk upgrade
        - apk add build-base linux-headers
        - ./configure --prefix=/usr && make && make install-strip

run_code_tests:
    image: ubuntu:trusty
    script:
        - apt-get update -qq
        - apt-get install -y -qq build-essential expect csh xzdec lintian fakeroot
        - ( ./configure --prefix=/usr && make && make install && make test-travis )
